BretanoWebMiddle/Orkidea.Bretano.WebMiddle.FrontEnd/Controllers/SalesOrderController.cs
using Orkidea.Bretano.WebMiddle.FrontEnd.Business;
using Orkidea.Bretano.WebMiddle.FrontEnd.Entities;
using Orkidea.Bretano.WebMiddle.FrontEnd.Models;
using Orkidea.Bretano.WebMiddle.FrontEnd.WebMiddleBackEnd;
using Orkidea.Framework.Security;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Principal;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Xml.Serialization;

namespace Orkidea.Bretano.WebMiddle.FrontEnd.Controllers
{
    public class SalesOrderController : Controller
    {
        WSSAPClient backEnd = new WSSAPClient();

        public ActionResult Index()
        {
            #region User identification
            IIdentity context = HttpContext.User.Identity;
            string userId = "";
            bool admin = false;
            bool customerCreator = false;
            bool purchaseOrderCreator = false;
            int companyId = 0;
            string userName = "";
            AppConnData appConnData = new AppConnData();

            if (context.IsAuthenticated)
            {

                System.Web.Security.FormsIdentity ci = (System.Web.Security.FormsIdentity)HttpContext.User.Identity;
                string[] userRole = ci.Ticket.UserData.Split('|');
                userId = userRole[0];
                admin = int.Parse(userRole[1]) == 1 ? true : false;
                customerCreator = int.Parse(userRole[2]) == 1 ? true : false;
                purchaseOrderCreator = int.Parse(userRole[3]) == 1 ? true : false;
                companyId = int.Parse(userRole[4]);
                userName = ci.Name;
                appConnData = GetAppConnData(companyId);
            }
            #endregion

            List<CompanyParameter> companyParameters = BizCompanyParameter.GetList(companyId).ToList();
            string MaxOlderOrderDays = companyParameters.Where(x => x.idParameter.Equals(4)).Select(x => x.value).FirstOrDefault();
            string batchMarketingTransactions = companyParameters.Where(x => x.idParameter.Equals(5)).Select(x => x.value).FirstOrDefault();

            List<ORDR> orders = BizSalesOrderDraft.GetPendingList(userId, companyId, int.Parse(MaxOlderOrderDays))
                //.Where(x => x.draftDM.Equals(false) && x.draftLC.Equals(false))
                .ToList();

            List<ORDRViewModel> listOrders = new List<ORDRViewModel>();
            List<ProcessQueue> pendingByProcess = BizProcessQueue.GetList(companyId, int.Parse(MaxOlderOrderDays)).ToList();
            vmOrderQueue model = new vmOrderQueue();

            foreach (ORDR item in orders)
            {
                if (batchMarketingTransactions == "Si")
                {
                    if (pendingByProcess.Where(x => x.actionType == "A" && x.idTarget.Equals(item.id)).Count() == 0)
                    {
                        ORDRViewModel order = new ORDRViewModel()
                        {
                            id = HexSerialization.StringToHex(item.id.ToString()),
                            cardCode = item.cardCode,
                            cardName = !string.IsNullOrEmpty(item.cardName) ? item.cardName : "",
                            docDate = item.docDate,
                            comment = item.docEntry == null ? "No finalizada" : "Enviada a SAP correctamente",
                            editable = item.docEntry == null ? true : false,
                        };

                        listOrders.Add(order);
                        //model.openOrders.Add(order);
                    }
                    else
                    {
                        ProcessQueue orderProcess = pendingByProcess.Where(x => x.actionType == "A" && x.idTarget.Equals(item.id)).FirstOrDefault();
                        ORDRViewModel order = new ORDRViewModel()
                        {
                            id = HexSerialization.StringToHex(item.id.ToString()),
                            cardCode = item.cardCode,
                            cardName = !string.IsNullOrEmpty(item.cardName) ? item.cardName : "",
                            docDate = item.docDate,
                            editable = false
                        };

                        if (orderProcess.processed == null)
                            order.comment = "En cola";
                        else
                        {
                            if (orderProcess.logMessage.Substring(0, 5) == "Error")
                                order.redo = true;
                            else
                                order.redo = false;

                            order.comment = string.Format("{0}", orderProcess.logMessage);
                        }
                        listOrders.Add(order);
                    }
                }
                else
                {
                    ORDRViewModel order = new ORDRViewModel()
                    {
                        id = HexSerialization.StringToHex(item.id.ToString()),
                        cardCode = item.cardCode,
                        cardName = !string.IsNullOrEmpty(item.cardName) ? item.cardName : "",
                        docDate = item.docDate,
                        comment = item.docEntry == null ? "No finalizada" : "Enviada a SAP correctamente",
                        editable = item.docEntry == null ? true : false
                    };

                    listOrders.Add(order);
                }


            }

            return View(listOrders.OrderByDescending(x => x.docDate).ToList());
        }

        //
        // GET: /SalesOrder/
        [Authorize]
        public ActionResult itemIndex(string id)
        {
            ViewBag.id = id;
            return View();
        }

        [Authorize]
        public ActionResult Create()
        {
            #region User identification
            IIdentity context = HttpContext.User.Identity;
            string userId = "";
            bool admin = false;
            bool customerCreator = false;
            bool purchaseOrderCreator = false;
            int companyId = 0;
            string userName = "";
            AppConnData appConnData = new AppConnData();

            if (context.IsAuthenticated)
            {

                System.Web.Security.FormsIdentity ci = (System.Web.Security.FormsIdentity)HttpContext.User.Identity;
                string[] userRole = ci.Ticket.UserData.Split('|');
                userId = userRole[0];
                admin = int.Parse(userRole[1]) == 1 ? true : false;
                customerCreator = int.Parse(userRole[2]) == 1 ? true : false;
                purchaseOrderCreator = int.Parse(userRole[3]) == 1 ? true : false;
                companyId = int.Parse(userRole[4]);
                userName = ci.Name;
                appConnData = GetAppConnData(companyId);
            }
            #endregion

            List<CompanyParameter> companyParameters = BizCompanyParameter.GetList(companyId).ToList();
            string defaulSeries = companyParameters.Where(x => x.idParameter.Equals(8)).Select(x => x.value).FirstOrDefault();
            string ShowOnlyCustomerGroupNum = companyParameters.Where(x => x.idParameter.Equals(9)).Select(x => x.value).FirstOrDefault();

            ViewBag.defaulSeries = string.IsNullOrEmpty(defaulSeries) ? "" : defaulSeries;
            ViewBag.ShowOnlyCustomerGroupNum = string.IsNullOrEmpty(ShowOnlyCustomerGroupNum) ? "No" : ShowOnlyCustomerGroupNum;

            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(ORDR order)
        {
            #region User identification
            IIdentity context = HttpContext.User.Identity;
            string userId = "";
            bool admin = false;
            bool customerCreator = false;
            bool purchaseOrderCreator = false;
            int companyId = 0;
            string userName = "";
            int slpCode = 0;
            AppConnData appConnData = new AppConnData();

            if (context.IsAuthenticated)
            {

                System.Web.Security.FormsIdentity ci = (System.Web.Security.FormsIdentity)HttpContext.User.Identity;
                string[] userRole = ci.Ticket.UserData.Split('|');

                userId = userRole[0];
                admin = int.Parse(userRole[1]) == 1 ? true : false;
                customerCreator = int.Parse(userRole[2]) == 1 ? true : false;
                purchaseOrderCreator = int.Parse(userRole[3]) == 1 ? true : false;
                companyId = int.Parse(userRole[4]);
                slpCode = int.Parse(userRole[5]);
                userName = ci.Name;
                appConnData = GetAppConnData(companyId);
            }
            #endregion

            List<CompanyParameter> companyParameters = BizCompanyParameter.GetList(companyId).ToList();
            string defaulSeries = companyParameters.Where(x => x.idParameter.Equals(8)).Select(x => x.value).FirstOrDefault();

            if (!string.IsNullOrEmpty(defaulSeries))
            {
                List<DocumentSeries> docSeries = backEnd.GetDocumentSeriesList(SapDocumentType.SalesOrder, appConnData);
                int serie = docSeries.Where(x => x.seriesName == defaulSeries).Select(x => x.series).FirstOrDefault();

                if (serie != null)
                    order.series = serie;

            }

            order.uOrkUsuarioWeb = userId;
            order.idCompania = companyId;
            order.slpCode = slpCode;
            order.uLatitud = !string.IsNullOrEmpty(order.uLatitud) ? order.uLatitud : "4.690449";
            order.uLongitud = !string.IsNullOrEmpty(order.uLongitud) ? order.uLongitud : "-74.0515331";

            var myTimeZone = TimeZoneInfo.FindSystemTimeZoneById("SA Pacific Standard Time");

BretanoWebMiddle/Orkidea.Bretano.WebMiddle.FrontEnd/Views/SalesOrder/Approve.cshtml
@model Orkidea.Bretano.WebMiddle.FrontEnd.Entities.ORDR
@{
    ViewBag.Title = "ViewOrder";
    Layout = null;
}
<div class="container-fluid" style="margin-left: 25px;">
    @using (Html.BeginForm("Approve", "SalesOrder", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="form-group">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.authComments, "Comentarios de la autorización", new { @class = "control-label" })
                    @Html.TextAreaFor(m => m.authComments, new { @class = "form-control", title = "id del contacto", rows = 7 })
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <input type='submit' id='upload-files' value=' Terminar ' class="btn btn-info" />
                </div>
            </div>
        </div>
    }
</div>

BretanoWebMiddle/Orkidea.Bretano.WebMiddle.FrontEnd/Views/SalesOrder/AuthorizationDetailReport.cshtml
@{
    ViewBag.Title = "AuthorizationDetailReport";
}

<h2>Reporte autorizaciones</h2>
<div class="row">
    <div class="form-group">
        <div class="col-md-2">
            @Html.Label("Desde", new { @for = "start", @class = "control-label" })
            <div class="input-group date dtPicker" id="datetimepicker1">
                <input type="text" class="form-control" id="start" />
                <span class="input-group-addon">
                    <span class="fa fa-calendar"></span>
                </span>
            </div>
        </div>
        <div class="col-md-2">
            @Html.Label("Hasta", new { @for = "end", @class = "control-label" })
            <div class="input-group date dtPicker" id="datetimepicker2">
                <input type="text" class="form-control" id="end" />
                <span class="input-group-addon">
                    <span class="fa fa-calendar"></span>
                </span>
            </div>
        </div>        
        <div class="col-md-1">
            <label class="control-label" style="color:white">.</label>
            <input type="button" value="Buscar" id="btnSearch" class="btn btn-info" />
        </div>
        <div class="col-md-1">
            <label class="control-label" style="color:white">.</label>
            <input type="button" value="Descargar" id="btnExport" class="btn btn-info" />
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-12">
        <table id="requests" class="display" cellspacing="0">
            <thead>
                <tr>
                    <th>Cliente</th>
                    <th>Pedido</th>
                    <th>Fecha</th>
                    <th>Valor</th>
                    <th>Comentarios</th>
                    <th>Estado</th>
                    <th>Autorizador</th>
                    <th>Autorizado</th>
                    <th>Observaciones</th>                    
                </tr>
            </thead>
        </table>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.dtPicker').datepicker({
            format: "yyyy-mm-dd",
            todayBtn: "linked",
            language: "es",
            orientation: "bootom auto",
            autoclose: true,
            todayHighlight: true,
            toggleActive: true
        });

        var fisrtDay = new Date();
        var today = new Date();

        var dd = today.getDate();
        var mm = today.getMonth() + 1; //January is 0!
        var yyyy = today.getFullYear();

        if (dd < 10) {
            dd = '0' + dd
        }

        if (mm < 10) {
            mm = '0' + mm
        }

        firstDay = yyyy + '-' + mm + '-01';
        today = yyyy + '-' + mm + '-' + dd ;


        $("#start").val(firstDay);
        $("#end").val(today);


        InitOverviewDataTable();

        $("#btnSearch").click(function () {
            RefreshTable();
        });

        $("#btnExport").click(function () {
            ExportData();
        });

        function InitOverviewDataTable() {
            var from, to;

            from = $("#start").val();
            to = $("#end").val();

            var url = "../SalesOrder/AsyncAuthReport/" + from + "|" + to;

            oOverviewTable = $('#requests').dataTable({
                //processing: true,
                "ajax": url,
                "order": [],
                "language": {
                    //"processing": "Hang on. Waiting for response...",
                    "lengthMenu": "Mostrar _MENU_ registros por pagina",
                    //"zeroRecords": "Ningun resultado encontrado",
                    "sLoadingRecords": "Obteniendo los clientes, espere un momento...",
                    "info": "Página _PAGE_ de _PAGES_",
                    "infoEmpty": "Sin registros",
                    "infoFiltered": "(filtered from _MAX_ total records)",
                    "search": "Buscar:",
                    "paginate": {
                        "first": "Primera",
                        "last": "Ultima",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    },
                }
            });
        }


        function RefreshTable() {
            from = $("#start").val();
            to = $("#end").val();

            var tableId = '#requests';
            var urlData = "../SalesOrder/AsyncAuthReport/" + from + "|" + to;

            $.getJSON(urlData, null, function (json) {
                table = $(tableId).dataTable();
                oSettings = table.fnSettings();
                table.fnClearTable(this);

                for (var i = 0; i < json.data.length; i++) {
                    table.oApi._fnAddData(oSettings, json.data[i]);
                }

                oSettings.aiDisplay = oSettings.aiDisplayMaster.slice();
                table.fnDraw();
            });
        }        

        function ExportData() {

            from = $("#start").val();
            to = $("#end").val();

            var tableId = '#requests';
            var urlData = "../SalesOrder/AsyncAuthReportXls/" + from + "|" + to;

            window.location = urlData;
        }

    });
</script>

BretanoWebMiddle/Orkidea.Bretano.WebMiddle.FrontEnd/Views/SalesOrder/AuthorizationReport.cshtml
@model IEnumerable<Orkidea.Bretano.WebMiddle.FrontEnd.Models.ORDRViewModel>
@{
    ViewBag.Title = "Index";           
}

<script src="~/Scripts/Custom/ordrIndex.js"></script>

<div class="container-fluid">
    <h2>Autorizaciones</h2>
    
    <br />
    <div class="row">
        <table id="ordr" class="display" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Fecha</th>
                    <th>Código</th>
                    <th>Cliente</th>
                    <th>Causa</th>
                    <th>Estado</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    string status = "";

                    if (item.status == null)
                    {
                        status = "Pendiente";
                    }
                    else
                    {
                        status = (bool)item.status ? "Aprobado" : "Rechazado";
                    }
                    
                    <tr>
                        <td>@item.docDate.ToString("yyyy-MM-dd hh:mm")</td>
                        <td>@item.cardCode</td>
                        <td>@item.cardName</td>
                        <td>@item.comment</td>
                        <td>@status</td>
                        <td>
                            <a href="@Url.Action("ViewOrder", new { id = item.id })" class="sepV_a" title="Ver orden"><i class="fa fa-search-plus"></i></a>                            
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>


@*@{
    ViewBag.Title = "AuthorizationReport";
}
<script src="~/Scripts/Custom/ordrAuthorizacionReport.js"></script>

<h2>Reporte de autorizaciones</h2>

<div class="row">
    <div class="form-group">
        <div class="col-md-2">
            @Html.Label("Desde", new { @for = "start", @class = "control-label" })
            <div class="input-group date dtPicker" id="datetimepicker1">
                <input type="text" class="form-control" id="start" />
                <span class="input-group-addon">
                    <span class="fa fa-calendar"></span>
                </span>
            </div>
        </div>
        <div class="col-md-2">
            @Html.Label("Hasta", new { @for = "end", @class = "control-label" })
            <div class="input-group date dtPicker" id="datetimepicker2">
                <input type="text" class="form-control" id="end" />
                <span class="input-group-addon">
                    <span class="fa fa-calendar"></span>
                </span>
            </div>
        </div>
        <div class="col-md-1">
            <label class="control-label" style="color:white">.</label>
            <input type="button" value="Buscar" id="btnSearch" class="btn btn-info" />
        </div>
    </div>
</div>
<hr />
<div class="row ordersTable">

</div>*@

BretanoWebMiddle/Orkidea.Bretano.WebMiddle.FrontEnd/Views/SalesOrder/Details.cshtml
@model Orkidea.Bretano.WebMiddle.FrontEnd.WebMiddleBackEnd.LightMarketingDocument
@{
    ViewBag.Title = "Details";
    double totalPedido = 0;
}

<script src="~/Scripts/Custom/ordrDetails.js"></script>

<h2>Detalle pedido</h2>
<div class="row">
    <div class="well">
        <div class="row">
            <div class="form-group">
                <div class="col-md-2">
                    <label class="control-label">Pedido</label>
                    <input type="text" class="form-control" value="@Model.docNum" id="docNum" style="max-width:100%" disabled />
                    <input type="text" class="form-control" value="@Model.docEntry" id="docEntry" style="max-width:100%; display:none"  />
                </div>
                <div class="col-md-3">
                    <label class="control-label">Cliente</label>
                    <input type="text" class="form-control" value="@Model.cardCode" id="cardCode" style="max-width:100%" disabled />
                </div>
                <div class="col-md-7">
                    <label class="control-label">Nombre</label>
                    <input type="text" class="form-control" value="@Model.cardName" id="cardName" style="max-width:100%" disabled />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group">
                <div class="col-md-2">
                    <label class="control-label">Fecha documento</label>
                    <input type="text" class="form-control" value="@Model.docDate.ToString("yyyy-MM-dd")" id="docDate" style="max-width:100%" disabled />
                </div>
                <div class="col-md-2">
                    <label class="control-label">Fecha entrega</label>
                    <input type="text" class="form-control" value="@Model.docDueDate.ToString("yyyy-MM-dd")" id="docDueDate" style="max-width:100%" disabled />
                </div>
                <div class="col-md-2">
                    <label class="control-label">Estatus</label>
                    <input type="text" class="form-control" value="@Model.docStatus" id="docStatus" style="max-width:100%" disabled />
                </div>
                <div class="col-md-2">
                    @if (Model.docStatus == "Abierto")
                    {
                        <input type="button" class="btn btn-danger" value="Cancelar Orden" id="btnCancel" style="margin-top: 25px;" />
                    }
                </div>

            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="well">
        <div class="row">
            <table class="table table-bordered table-striped table_vam" id="dt">
                <thead>
                    <tr>
                        <th>Articulo</th>
                        <th>Cantidad</th>
                        <th>Precio</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.lines)
                    {
                        double total = item.price * item.quantity;
                        totalPedido += total;
                        
                        
                        <tr>
                            <td>@item.itemCode <span> - </span> @item.itemName</td>
                            <td>@item.quantity</td>
                            <td>@item.price</td>                            
                            <td>@total</td>
                        </tr>
                    }
                </tbody>
            </table>

            <span><strong>Total Pedido: </strong>@ViewBag.total</span>
        </div>
    </div>
</div>

BretanoWebMiddle/Orkidea.Bretano.WebMiddle.FrontEnd/Views/SalesOrder/Draft.cshtml
@{
    ViewBag.Title = "Borrador de Pedido";
}

<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">El documento de borrador fue creado con éxito</h3>
    </div>
    <div class="panel-body">
        El documento de borrador fue creado exitosamente. 
        <br />
        @Html.ActionLink("Continuar", "DraftComments", "SalesOrder", new { id = ViewBag.id }, new { @class = "btn btn-success" })
    </div>
</div>

BretanoWebMiddle/Orkidea.Bretano.WebMiddle.FrontEnd/Views/SalesOrder/Finish.cshtml
@{
    ViewBag.Title = "Pedido";
}

<h2>Pedidos</h2>

<div class="panel panel-@ViewBag.colorMensaje">
    
    <div class="panel-heading">
        <h3 class="panel-title">@ViewBag.mensaje</h3>
    </div>
    <div class="panel-body">
        @ViewBag.docEntry
        <br />
        @Html.ActionLink("Aceptar", "Create", "SalesOrder", new { id = ViewBag.id }, new { @class = "btn btn-success" })
    </div>
</div>

BretanoWebMiddle/Orkidea.Bretano.WebMiddle.FrontEnd/Views/SalesOrder/Index.cshtml
@model IEnumerable<Orkidea.Bretano.WebMiddle.FrontEnd.Models.ORDRViewModel>
@{
    ViewBag.Title = "Index";
}

<script src="~/Scripts/Custom/ordrIndex.js"></script>

<div class="container-fluid">
    <h2>Pedidos</h2>
    <div class="row">
        @Html.ActionLink("Crear nuevo", "Create", null, new { @class = "btn btn-info" }) | @Html.ActionLink("Volver al home", "Index", "Home")
    </div>
    <br />
    <div class="row">
        <table id="ordr" class="display" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Fecha</th>
                    <th>Código</th>
                    <th>Cliente</th>
                    <th>Estatus</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.docDate.ToString("yyyy-MM-dd")</td>
                        <td>@item.cardCode</td>
                        <td>@item.cardName</td>
                        <td>@item.comment</td>
                        <td>
                            @if (item.editable == true)
                            {
                                <a href="@Url.Action("AddLine", new { id = item.id })" class="sepV_a" title="Editar"><i class="fa fa-pencil"></i></a>
                                <span>|</span>
                                <a href="@Url.Action("Remove", new { id = item.id })" title="Eliminar"><i class="fa fa-trash"></i></a>
                            }
                            else
                            {
                                if (item.redo)
                                {
                                    <a href="@Url.Action("AddLine", new { id = item.id })" class="sepV_a" title="Editar"><i class="fa fa-pencil"></i></a>
                                    <span> | </span>
                                    <a href="@Url.Action("tryAgain", new { id = item.id })" class="sepV_a" title="Reintentar"><i class="fa fa-refresh"></i></a>
                                }
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

BretanoWebMiddle/Orkidea.Bretano.WebMiddle.FrontEnd/Views/SalesOrder/ItemStock.cshtml
@{
    ViewBag.Title = "ItemStock";
}

<script src="~/Scripts/Custom/ItemStock.js"></script>

<h2>Inventario por artículo</h2>

<div class="row">
    <div class="form-group">
        <div class="col-md-2">
            <a href="javascript:void(0)" id="itemCodeLink" data-toggle="modal" data-target="#itemModal">@Html.Label("Código", new { @class = "control-label" })</a>
            <input type="text" class="form-control" id="itemCode" style="max-width:100%" disabled />
        </div>
        <div class="col-md-5">
            <label class="control-label">Nombre</label>
            <input type="text" class="form-control" value="" id="itemName" style="max-width:100%" disabled />
        </div>
        <div class="col-md-1">
            <label class="control-label" style="color:white">.</label>
            <input type="button" value="Buscar" id="btnSearch" class="btn btn-info" />
        </div>
    </div>
</div>
<br />
<div class="row stockBody">

</div>

<div class="modal fade" id="itemModal">
    <div class="modal-dialog modal-lg" style=" width:auto;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Artículos</h4>
            </div>
            <div class="modal-body">
                <table id="itemsTable" class="display" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Código</th>
                            <th>Nombre</th>
                            <th></th>
                        </tr>
                    </thead>
                </table>
            </div>
            <div class="modal-footer">
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

BretanoWebMiddle/Orkidea.Bretano.WebMiddle.FrontEnd/Views/SalesOrder/Reject.cshtml
@model Orkidea.Bretano.WebMiddle.FrontEnd.Entities.ORDR

@{
    ViewBag.Title = "ViewOrder";
    Layout = null;
}

<div class="container-fluid" style="margin-left: 25px;">
    @using (Html.BeginForm("Reject", "SalesOrder", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="form-group">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.authComments, "Comentarios de la autorización", new { @class = "control-label" })
                    @Html.TextAreaFor(m => m.authComments, new { @class = "form-control", title = "id del contacto", rows = 7 })
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <input type='submit' id='upload-files' value=' Terminar ' class="btn btn-info" />
                </div>
            </div>
        </div>
    }
</div>

BretanoWebMiddle/Orkidea.Bretano.WebMiddle.FrontEnd/Views/SalesOrder/SearchOrders.cshtml
@{
    ViewBag.Title = "itemIndex";
    Layout = null;
}
<table id="orders" class="display" cellspacing="0">
    <thead>
        <tr>
            <th>Pedido</th>
            <th>Fecha pedido</th>
            <th>Fecha entrega</th>
            <th>Estatus</th>
            <th></th>
        </tr>
    </thead>
</table>

<script>
    $(document).ready(function () {
        
        var id = '';

        var itemsTable = $('#orders').DataTable({
            //processing: true,
            "ajax": '@Url.Action("AsyncSearchOrders", new { id = ViewBag.data })',
            "columnDefs": [{
                "targets": -1,
                "data": null,
                "defaultContent": "<button data-dismiss='modal'>Ver</button>"
            }],
            "language": {
                //"processing": "Hang on. Waiting for response...",
                "lengthMenu": "Mostrar _MENU_ registros por pagina",
                //"zeroRecords": "Ningun resultado encontrado",
                "sLoadingRecords": "Obteniendo los clientes, espere un momento...",
                "info": "Página _PAGE_ de _PAGES_",
                "infoEmpty": "Sin registros",
                "infoFiltered": "(filtered from _MAX_ total records)",
                "search": "Buscar:",
                "paginate": {
                    "first": "Primera",
                    "last": "Ultima",
                    "next": "Siguiente",
                    "previous": "Anterior"
                },
            }
        });

        $('#orders tbody').on('click', 'button', function () {
            var data = itemsTable.row($(this).parents('tr')).data();
            var docNum = data[0];

            window.location = "@Url.Action("Details")" + "/" + docNum;
        });

    });
</script>