BretanoWebMiddle/Orkidea.Bretano.WebMiddle.FrontEnd/Controllers/QuotationController.cs
using Orkidea.Bretano.WebMiddle.FrontEnd.Business;
using Orkidea.Bretano.WebMiddle.FrontEnd.Entities;
using Orkidea.Bretano.WebMiddle.FrontEnd.WebMiddleBackEnd;
using Orkidea.Framework.Security;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Security.Principal;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;

namespace Orkidea.Bretano.WebMiddle.FrontEnd.Controllers
{
    public class QuotationController : Controller
    {
        WSSAPClient backEnd = new WSSAPClient();

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(OQUT quotation)
        {
            #region User identification
            IIdentity context = HttpContext.User.Identity;
            string userId = "";
            bool admin = false;
            bool customerCreator = false;
            bool purchaseOrderCreator = false;
            int companyId = 0;
            string userName = "";
            int slpCode = 0;
            AppConnData appConnData = new AppConnData();

            if (context.IsAuthenticated)
            {

                System.Web.Security.FormsIdentity ci = (System.Web.Security.FormsIdentity)HttpContext.User.Identity;
                string[] userRole = ci.Ticket.UserData.Split('|');

                userId = userRole[0];
                admin = int.Parse(userRole[1]) == 1 ? true : false;
                customerCreator = int.Parse(userRole[2]) == 1 ? true : false;
                purchaseOrderCreator = int.Parse(userRole[3]) == 1 ? true : false;
                companyId = int.Parse(userRole[4]);
                slpCode = int.Parse(userRole[5]);
                userName = ci.Name;
                appConnData = GetAppConnData(companyId);
            }
            #endregion

            quotation.uOrkUsuarioWeb = userId;
            quotation.idCompania = companyId;
            quotation.slpCode = slpCode;
            int orderNum = BizQuotation.Add(quotation);
            return RedirectToAction("AddLine", new { id = HexSerialization.StringToHex(orderNum.ToString()) });
        }

        [Authorize]
        public ActionResult AddLine(string id)
        {
            #region User identification
            IIdentity context = HttpContext.User.Identity;
            bool admin = false;
            bool customerCreator = false;
            bool purchaseOrderCreator = false;
            int companyId = 0;
            string userName = "";
            AppConnData appConnData = new AppConnData();

            if (context.IsAuthenticated)
            {

                System.Web.Security.FormsIdentity ci = (System.Web.Security.FormsIdentity)HttpContext.User.Identity;
                string[] userRole = ci.Ticket.UserData.Split('|');

                admin = int.Parse(userRole[1]) == 1 ? true : false;
                customerCreator = int.Parse(userRole[2]) == 1 ? true : false;
                purchaseOrderCreator = int.Parse(userRole[3]) == 1 ? true : false;
                companyId = int.Parse(userRole[4]);
                userName = ci.Name;
                appConnData = GetAppConnData(companyId);
            }
            #endregion

            string realId = HexSerialization.HexToString(id);
            OQUT OQUT = BizQuotation.GetSingle(int.Parse(realId));

            BusinessPartner customer = backEnd.GetBusinessPartner(OQUT.cardCode, appConnData);


            ViewBag.serie = backEnd.GetDocumentSeriesSingle(OQUT.series, appConnData).seriesName;
            ViewBag.cardCode = OQUT.cardCode;
            ViewBag.cardName = customer.cardName;
            ViewBag.docDate = OQUT.docDate.ToString("yyyy-MM-dd");
            ViewBag.docDueDate = OQUT.docDueDate.ToString("yyyy-MM-dd");
            ViewBag.taxDate = OQUT.taxDate.ToString("yyyy-MM-dd");
            ViewBag.uCssComentarios = OQUT.uCssComentarios;
            ViewBag.listNum = customer.listNum;
            ViewBag.orderId = realId;
            ViewBag.id = id;
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult AddLine(string id, QUT1 line)
        {
            string realId = HexSerialization.HexToString(id);
            line.orderId = int.Parse(realId);
            BizQuotation.AddLine(line);
            return RedirectToAction("AddLine", new { id = id });
        }

        [Authorize]
        public ActionResult Finish(string id)
        {
            try
            {
                #region User identification
                IIdentity context = HttpContext.User.Identity;
                int user = 0;
                bool admin = false;
                bool customerCreator = false;
                bool purchaseOrderCreator = false;
                int companyId = 0;
                string userName = "";
                int slpCode = 0;
                AppConnData appConnData = new AppConnData();

                if (context.IsAuthenticated)
                {

                    System.Web.Security.FormsIdentity ci = (System.Web.Security.FormsIdentity)HttpContext.User.Identity;
                    string[] userRole = ci.Ticket.UserData.Split('|');
                    user = int.Parse(userRole[0]);
                    admin = int.Parse(userRole[1]) == 1 ? true : false;
                    customerCreator = int.Parse(userRole[2]) == 1 ? true : false;
                    purchaseOrderCreator = int.Parse(userRole[3]) == 1 ? true : false;
                    companyId = int.Parse(userRole[4]);
                    slpCode = int.Parse(userRole[5]);
                    userName = ci.Name;
                    appConnData = GetAppConnData(companyId);
                }
                #endregion

                string realId = HexSerialization.HexToString(id);
                OQUT OQUT = BizQuotation.GetSingle(int.Parse(realId));
                List<QUT1> lines = BizQuotation.GetLinesList(int.Parse(realId)).ToList();

                MarketingDocument document = new MarketingDocument()
                {
                    cardCode = OQUT.cardCode,
                    serie = OQUT.series,
                    docDate = OQUT.docDate,
                    docDueDate = OQUT.docDueDate,
                    taxDate = OQUT.taxDate,
                    shipToCode = OQUT.shipToCode,
                    payToCode = OQUT.payToCode,
                    lines = new List<MarketingDocumentLine>(),
                    userDefinedFields = new List<UserDefinedField>()
                };

                if (slpCode > 0)
                    document.slpCode = slpCode;

                document.userDefinedFields.Add(new UserDefinedField()
                {
                    name = "U_CSS_COMENTARIOS",
                    type = UdfType.Text,
                    value = OQUT.uCssComentarios
                });

                foreach (QUT1 item in lines)
                {

                    MarketingDocumentLine line = new MarketingDocumentLine()
                    {
                        itemCode = item.itemCode,
                        quantity = (double)item.quantity,
                        whsCode = item.whsCode,
                        taxCode = item.taxCode,
                        ocrCode = item.ocrCode,
                        price = (double)item.price,
                        batchNumbers = new List<BatchNumber>(),
                        serialNumbers = new List<SerialNumber>(),
                        userDefinedFields = new List<UserDefinedField>()
                    };

                    line.userDefinedFields.Add(new UserDefinedField()
                    {
                        name = "U_CSS_ENVASEDEVOL",
                        type = UdfType.Alphanumeric,
                        value = item.uCssEnvaseDevol
                    });

                    document.lines.Add(line);
                }

                if (userName.ToLower() != "root")
                {
                    WebUserCompany wuc = BizWebUserCompany.GetSingle(user, companyId);
                    if (wuc.slpCode != 0)
                        document.slpCode = wuc.slpCode;
                }


                document = backEnd.AddQuotation(document, appConnData);
                ViewBag.colorMensaje = "success";
                ViewBag.mensaje = "Cotización creada con éxito";
                ViewBag.docEntry = string.Format("Se creó la cotización no {0}", document.docEntry);

                OQUT.docEntry = document.docEntry;
                BizQuotation.Update(OQUT);
            }
            catch (FaultException<DataAccessFault> ex)
            {
                ViewBag.colorMensaje = "danger";
                ViewBag.mensaje = "No se pudo crear la Cotización";
                ViewBag.docEntry = string.Format("Codigo {0} error:{1} {2}", ex.Code, ex.Detail.Description, ex.Message);
            }
            return View();
        }

        [Authorize]
        //[OutputCache(Duration = int.MaxValue, VaryByParam = "none")]
        public JsonResult AsyncSeriesList()
        {
            #region User identification
            IIdentity context = HttpContext.User.Identity;
            bool admin = false;
            bool customerCreator = false;
            bool purchaseOrderCreator = false;
            int companyId = 0;
            string userName = "";
            AppConnData appConnData = new AppConnData();

            if (context.IsAuthenticated)
            {

                System.Web.Security.FormsIdentity ci = (System.Web.Security.FormsIdentity)HttpContext.User.Identity;
                string[] userRole = ci.Ticket.UserData.Split('|');

                admin = int.Parse(userRole[1]) == 1 ? true : false;
                customerCreator = int.Parse(userRole[2]) == 1 ? true : false;
                purchaseOrderCreator = int.Parse(userRole[3]) == 1 ? true : false;

BretanoWebMiddle/Orkidea.Bretano.WebMiddle.FrontEnd/Views/Quotation/AddLine.cshtml
@model Orkidea.Bretano.WebMiddle.FrontEnd.Entities.QUT1

@{
    ViewBag.Title = "Cotizaciones::lineas";
}

<script src="~/Scripts/Custom/QuotationLineCreate.js"></script>

<div class="container-fluid">
    @using (Html.BeginForm("AddLine", "Quotation", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <h2>Cotizaciones</h2>

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="well">
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-2">
                            <label class="control-label">Serie</label>
                            <input type="text" class="form-control" value="@ViewBag.serie" id="serie" style="max-width:100%" disabled />
                        </div>
                        <div class="col-md-3">
                            <label class="control-label">Cliente</label>
                            <input type="text" class="form-control" value="@ViewBag.cardCode" id="cardCode" style="max-width:100%" disabled />
                        </div>
                        <div class="col-md-7">
                            <label class="control-label">Nombre</label>
                            <input type="text" class="form-control" value="@ViewBag.cardName" id="cardName" style="max-width:100%" disabled />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-2">
                            <label class="control-label">Fecha documento</label>
                            <input type="text" class="form-control" value="@ViewBag.docDate" id="docDate" style="max-width:100%" disabled />
                        </div>
                        <div class="col-md-2">
                            <label class="control-label">Fecha entrega</label>
                            <input type="text" class="form-control" value="@ViewBag.docDueDate" id="docDueDate" style="max-width:100%" disabled />
                        </div>
                        <div class="col-md-2">
                            <label class="control-label">Fecha contabilización</label>
                            <input type="text" class="form-control" value="@ViewBag.taxDate" id="taxDate" style="max-width:100%" disabled />
                        </div>
                        <div class="col-md-2">
                            <input type="text" class="form-control" value="@ViewBag.listNum" id="listNum" style="max-width:100%; visibility:hidden" disabled />
                        </div>
                        <div class="col-md-2">
                            <input type="text" class="form-control" value="@ViewBag.orderId" id="orderId" style="max-width:100%; visibility:hidden" disabled />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-12">
                            <label class="control-label">Comentarios</label>
                            <textarea class="form-control" rows="5" readonly>@ViewBag.uCssComentarios</textarea>
                        </div>

                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-5">
                            <div class="row">
                                <div class="form-group">
                                    <div class="col-md-4">
                                        <a href="javascript:void(0);" data-toggle="modal" data-target="#itemModal">@Html.LabelFor(model => model.itemCode, "Codigo artículo", new { @class = "control-label" })</a>
                                        @Html.TextBoxFor(m => m.itemCode, new { @class = "form-control", title = "Código del artículo", readOnly = true })
                                        @Html.ValidationMessageFor(m => m.itemCode, "Requerido", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-md-8">
                                        <label class="control-label">Nombre artículo</label>
                                        <input type="text" class="form-control" id="itemName" style="max-width:100%" disabled />
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <div class="col-md-4">
                                        <a href="javascript:void(0);" id="whsLink">@Html.LabelFor(model => model.whsCode, "Codigo almacén", new { @class = "control-label" })</a>
                                        @Html.TextBoxFor(m => m.whsCode, new { @class = "form-control required", title = "Código de cliente sin digito de verificación", readOnly = true })
                                        @Html.ValidationMessageFor(m => m.whsCode, "Requerido", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-md-8">
                                        <label class="control-label">Nombre almacen</label>
                                        <input type="text" class="form-control" id="whsName" style="max-width:100%" disabled />
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <div class="col-md-4">
                                        @Html.LabelFor(model => model.price, "Precio", new { @class = "control-label" })
                                        @Html.TextBoxFor(m => m.price, new { @class = "form-control required", title = "Código de cliente sin digito de verificación", readOnly = true })
                                        @Html.ValidationMessageFor(m => m.price, "Requerido", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-md-4">
                                        @Html.LabelFor(model => model.quantity, "Cantidad", new { @class = "control-label" })
                                        @Html.TextBoxFor(m => m.quantity, new { @class = "form-control required", title = "Código de cliente sin digito de verificación" })
                                        @Html.ValidationMessageFor(m => m.quantity, "Requerido", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-md-4">
                                        @Html.LabelFor(model => model.taxCode, "Codigo impuestos", new { @class = "control-label" })
                                        @Html.DropDownListFor(model => model.taxCode, new SelectList(Enumerable.Empty<SelectListItem>()), " ", new { @class = "form-control required", style = "max-width:100%" })
                                        @Html.ValidationMessageFor(m => m.taxCode, "Requerido", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <div class="col-md-8">
                                        @Html.LabelFor(model => model.ocrCode, "Norma de reparto", new { @class = "control-label" })
                                        @Html.DropDownListFor(model => model.ocrCode, new SelectList(Enumerable.Empty<SelectListItem>()), " ", new { @class = "form-control required", style = "max-width:100%" })
                                        @Html.ValidationMessageFor(m => m.ocrCode, "Requerido", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-md-4">
                                        @Html.LabelFor(model => model.uCssEnvaseDevol, "Envase devolutivo", new { @class = "control-label" })
                                        @Html.DropDownListFor(model => model.uCssEnvaseDevol, new SelectList(Enumerable.Empty<SelectListItem>()), " ", new { @class = "form-control required", style = "max-width:100%" })
                                        @Html.ValidationMessageFor(m => m.uCssEnvaseDevol, "Requerido", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <table id="ordrLines" class="display" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>item</th>
                                        <th>Cantidad</th>
                                        <th>Precio</th>
                                        <th>Total</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th colspan="3" style="text-align:right">Total:</th>
                                        <th></th>
                                    </tr>

                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type='submit' value=' Agregar linea ' class="btn btn-info" />
                            | @Html.ActionLink("Terminar", "finish", "Quotation", new { id = ViewBag.id }, new { @class = "btn btn-success" })
                            | @Html.ActionLink("Cancelar", "cancel", "Quotation", new { @class = "btn btn-danger" })
                        </div>
                    </div>
                </div>
            </div>


        </div>

        <div class="modal fade" id="itemModal">
            <div class="modal-dialog modal-lg" style=" width:auto;">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Artículos</h4>
                    </div>
                    <div class="modal-body">
                        <table id="itemsTable" class="display" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Código</th>
                                    <th>Nombre</th>
                                    <th></th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                    <div class="modal-footer">
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->

        <div class="modal fade" id="whsModal">
            <div class="modal-dialog modal-lg" style=" width:auto;">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Artículos</h4>
                    </div>
                    <div class="modal-body stockBody">

                    </div>
                    <div class="modal-footer">
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->

    }
</div>

BretanoWebMiddle/Orkidea.Bretano.WebMiddle.FrontEnd/Views/Quotation/Finish.cshtml
@{
    ViewBag.Title = "Cotización";
}

<div class="panel panel-@ViewBag.colorMensaje">
    <div class="panel-heading">
        <h3 class="panel-title">@ViewBag.mensaje</h3>
    </div>
    <div class="panel-body">
        @ViewBag.docEntry
        <br />
        @Html.ActionLink("Aceptar", "Create", "Quotation", new { id = ViewBag.id }, new { @class = "btn btn-success" })
    </div>
</div>