BretanoWebMiddle/Orkidea.Bretano.WebMiddle.FrontEnd/Controllers/CompanyController.cs
using Orkidea.Bretano.WebMiddle.FrontEnd.Business;
using Orkidea.Bretano.WebMiddle.FrontEnd.Entities;
using Orkidea.Bretano.WebMiddle.FrontEnd.Models;
using Orkidea.Framework.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Orkidea.Bretano.WebMiddle.FrontEnd.Controllers
{
    public class CompanyController : Controller
    {
        //
        // GET: /Company/
        [Authorize]
        public ActionResult Index()
        {
            List<Company> companies = BizCompany.GetList().ToList();
            return View(companies);
        }

        //
        // GET: /Company/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Company/Create
        [HttpPost]
        [Authorize]
        public ActionResult Create(Company company)
        {
            try
            {
                company.dataBaseName = HexSerialization.StringToHex(Cryptography.Encrypt(company.dataBaseName));
                company.connStringName = HexSerialization.StringToHex(Cryptography.Encrypt(company.connStringName));
                company.sapUser = HexSerialization.StringToHex(Cryptography.Encrypt(company.sapUser));
                company.sapPassword = HexSerialization.StringToHex(Cryptography.Encrypt(company.sapPassword));

                BizCompany.Add(company);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Company/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            Company company = BizCompany.GetSingle(id);

            company.dataBaseName = Cryptography.Decrypt(HexSerialization.HexToString(company.dataBaseName));
            company.connStringName = Cryptography.Decrypt(HexSerialization.HexToString(company.connStringName));
            company.sapUser = Cryptography.Decrypt(HexSerialization.HexToString(company.sapUser));
            company.sapPassword = Cryptography.Decrypt(HexSerialization.HexToString(company.sapPassword));

            return View(company);
        }

        //
        // POST: /Company/Edit/5
        [HttpPost]
        [Authorize]
        public ActionResult Edit(int id, Company company)
        {
            try
            {
                company.dataBaseName = HexSerialization.StringToHex(Cryptography.Encrypt(company.dataBaseName));
                company.connStringName = HexSerialization.StringToHex(Cryptography.Encrypt(company.connStringName));
                company.sapUser = HexSerialization.StringToHex(Cryptography.Encrypt(company.sapUser));
                company.sapPassword = HexSerialization.StringToHex(Cryptography.Encrypt(company.sapPassword));
                company.id = id;

                BizCompany.Update(company);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [Authorize]
        public ActionResult Setup(int id)
        {
            Company company = BizCompany.GetSingle(id);

            List<Parameter> parameters = BizParameter.GetList().ToList();
            List<CompanyParameter> companyParameters = BizCompanyParameter.GetList(id).ToList();
            List<CompanyParameterViewModel> comParameters = new List<CompanyParameterViewModel>();

            #region Parameter Sync
            if (companyParameters.Count().Equals(0))
            {
                CompanyParameter[] cp = new CompanyParameter[parameters.Count()];

                for (int i = 0; i < parameters.Count(); i++)
                {
                    cp[i] = new CompanyParameter() { idCompany = id, idParameter = parameters[i].id };
                }

                BizCompanyParameter.Add(cp);

                companyParameters = BizCompanyParameter.GetList(id).ToList();
            }

            if (companyParameters.Count() < parameters.Count())
            {
                CompanyParameter[] cp = new CompanyParameter[parameters.Count() - companyParameters.Count()];

                int index = 0;

                for (int i = 0; i < parameters.Count(); i++)
                {                    
                    if (companyParameters.Where(x => x.idParameter.Equals(parameters[i].id)).Count().Equals(0))
                    {
                        cp[index] = new CompanyParameter() { idCompany = id, idParameter = parameters[i].id };
                        index++;
                    }                    
                }

                BizCompanyParameter.Add(cp);

                companyParameters = BizCompanyParameter.GetList(id).ToList();
            }
            #endregion

            foreach (Parameter item in parameters)
            {
                string value = "";

                if (item.type != "EncryptedText")
                    value = companyParameters.Where(x => x.idParameter.Equals(item.id)).Select(x => x.value).FirstOrDefault();
                else
                {
                    value = companyParameters.Where(x => x.idParameter.Equals(item.id)).Select(x => x.value).FirstOrDefault();

                    if (!string.IsNullOrEmpty(value))
                        value = Cryptography.Decrypt(HexSerialization.HexToString(value));
                    else
                        value = "";
                }

                comParameters.Add(new CompanyParameterViewModel()
                {
                    id = item.id,
                    label = item.label,
                    name = item.name,
                    type = item.type,
                    value = value
                });
            }
            //Cryptography.Decrypt(HexSerialization.HexToString(company.dataBaseName));
            ViewBag.idCompany = id;
            ViewBag.companyName = company.name;

            return View(comParameters);
        }

        public JsonResult SaveCompanySettings(List<CompanyParameter> CompanyParameters)
        {
            string res = "";

            try
            {
                CompanyParameter[] coParameters = new CompanyParameter[CompanyParameters.Count()];
                List<Parameter> parameters = BizParameter.GetList().ToList();

                for (int i = 0; i < CompanyParameters.Count(); i++)
                {
                    string type = parameters.Where(x => x.id.Equals(CompanyParameters[i].idParameter)).Select(x => x.type).FirstOrDefault();

                    if (type == "EncryptedText")
                    {
                        CompanyParameters[i].value = HexSerialization.StringToHex(Cryptography.Encrypt(CompanyParameters[i].value));
                    }
                    coParameters[i] = CompanyParameters[i];
                }

                BizCompanyParameter.Update(coParameters);

                res = "OK";
            }
            catch (Exception ex)
            {
                res = string.Format("Se presento un error inesperado Detalles {0}", ex.Message);
            }

            return Json(res, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /Company/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            BizCompany.Remove(new Company() { id = id });

            return RedirectToAction("Index");
        }
    }
}

BretanoWebMiddle/Orkidea.Bretano.WebMiddle.FrontEnd/Controllers/WebUserController.cs
using Orkidea.Bretano.WebMiddle.FrontEnd.Business;
using Orkidea.Bretano.WebMiddle.FrontEnd.Business.Enums;
using Orkidea.Bretano.WebMiddle.FrontEnd.Entities;
using Orkidea.Framework.Security;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Orkidea.Bretano.WebMiddle.FrontEnd.Controllers
{
    public class WebUserController : Controller
    {
        //
        // GET: /WebUser/
        [Authorize]
        public ActionResult Index()
        {            
            return View(BizWebUser.GetList());
        }

        //
       
        //
        // GET: /WebUser/Create
        [Authorize]
        public ActionResult Create()
        {
            int specialUser = int.Parse(Cryptography.Decrypt(HexSerialization.HexToString(ConfigurationManager.AppSettings["SpecialUser"])));
            int standarlUser = int.Parse(Cryptography.Decrypt(HexSerialization.HexToString(ConfigurationManager.AppSettings["StandarUser"])));

            int totalUsers = BizWebUser.GetList().Where(x => x.active).Count();

            if (totalUsers >= (specialUser + standarlUser))
                return RedirectToAction("index");

            return View();
        }

        //
        // POST: /WebUser/Create
        [HttpPost]
        [Authorize]
        public ActionResult Create(WebUser user)
        {
            try
            {
                user.pass = HexSerialization.StringToHex(Cryptography.Encrypt(user.pass));
                BizWebUser.Add(user);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /WebUser/Edit/5
        [Authorize]
        public ActionResult Enable(int id)
        {
            try
            {
                WebUser user = BizWebUser.GetSingle(id);
                BizWebUser.Update(WebUserAction.Enable, user);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // POST: /WebUser/Edit/5        
        [Authorize]
        public ActionResult Disable(int id)
        {
            try
            {
                WebUser user = BizWebUser.GetSingle(id);                
                BizWebUser.Update(WebUserAction.Disable, user);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /WebUser/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            WebUser user = BizWebUser.GetSingle(id);
            BizWebUser.Remove(user);
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Restore(int id)
        {
            WebUser user = BizWebUser.GetSingle(id);
            BizWebUser.Update(WebUserAction.UserReset,user);
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Asociate(int id) 
        {
            WebUser user = BizWebUser.GetSingle(id);

            ViewBag.WebUser = user.name;
            ViewBag.WebUserId = user.id;
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult Asociate(int id, WebUserCompany company)
        {
            company.webUserId = id;

            BizWebUserCompany.Add(company);
            return RedirectToAction("Asociate", new { id = id });
        }

        [Authorize]
        public ActionResult Deasociate(string id)
        {
            string[] data = id.Split('|');

            BizWebUserCompany.Remove(new WebUserCompany() { webUserId = int.Parse( data[0]), companyId = int.Parse(data[1]) });

            return RedirectToAction("Asociate", new { id = int.Parse(data[0]) });
        }

        [Authorize]
        public JsonResult AsyncFreeCompanyList(int id)
        {            
            List<Company> companies = BizCompany.GetList().ToList();
            List<WebUserCompany> usedCompanies = BizWebUserCompany.GetList().ToList();
            usedCompanies = usedCompanies.Where(x => x.webUserId.Equals(id)).ToList();

            List<Company> freeCompanies = new List<Company>();

            foreach (Company item in companies)
            {
                if (usedCompanies.Where(x => x.companyId.Equals(item.id)).Count() == 0)
                    freeCompanies.Add(item);
            }

            return Json(freeCompanies, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public JsonResult AsyncUsedCompanyList(int id)
        {
            List<Company> companies = BizCompany.GetList().ToList();
            List<WebUserCompany> userCompanies = BizWebUserCompany.GetList().Where(x => x.webUserId.Equals(id)).ToList();
            List<Company> usedCompanies= new List<Company>();

            foreach (Company item in companies)
            {
                if (userCompanies.Where(x => x.companyId.Equals(item.id)).Count() != 0)
                    usedCompanies.Add(item);
            }

            var data = from c in usedCompanies select new[] { c.id.ToString(), c.name };

            return Json(new
            {
                data = data
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

BretanoWebMiddle/Orkidea.Bretano.WebMiddle.FrontEnd/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Web Middleware</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href='http://fonts.googleapis.com/css?family=Russo+One|Patua+One|Exo' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.5/css/jquery.dataTables.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    @*<link rel="stylesheet" href="http://eternicode.github.io/bootstrap-datepicker/bootstrap-datepicker/css/datepicker3.css" />*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.1/css/bootstrap-datepicker3.css" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.5/js/jquery.dataTables.js"></script>
    @*<script type="text/javascript" charset="utf8" src="http://eternicode.github.io/bootstrap-datepicker/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>*@
    <script type="text/javascript" charset="utf-8" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.1/js/bootstrap-datepicker.min.js"></script>
    @*<script src="http://eternicode.github.io/bootstrap-datepicker/bootstrap-datepicker/js/locales/bootstrap-datepicker.es.js" charset="UTF-8"></script>*@
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.1/locales/bootstrap-datepicker.es.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>

    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-36281914-4', 'auto');
        ga('send', 'pageview');

    </script>

    <!-- font icons -->
    @{
        System.Security.Principal.IIdentity context = Context.User.Identity;
        bool admin = false;
        bool customerCreator = false;
        bool purchaseOrderCreator = false;
        bool orderApprover = false;
        string userName = "", company = "";
        bool supervisor = false;

        if (context.IsAuthenticated)
        {
            System.Web.Security.FormsIdentity ci = (System.Web.Security.FormsIdentity)Context.User.Identity;
            string[] userRole = ci.Ticket.UserData.Split('|');
            admin = int.Parse(userRole[1]) == 1 ? true : false;
            customerCreator = int.Parse(userRole[2]) == 1 ? true : false;
            purchaseOrderCreator = int.Parse(userRole[3]) == 1 ? true : false;
            company = userRole[6];
            userName = ci.Name;
            orderApprover = int.Parse(userRole[7]) == 1 ? true : false;
            supervisor = int.Parse(userRole[8]) == 1 ? true : false;
        }

    }

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })*@
                <a href="@Url.Action("Index","Home")"><img alt="Logo" class="logo" src="@Url.Content("~/images/Logo.png")" /></a>
            </div>
            <div class="navbar-collapse collapse">
                @if (context.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pedidos<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                @if (purchaseOrderCreator)
                                {
                                    <li>@Html.ActionLink("Gestionar pedidos", "index", "salesorder")</li>
                                    <li>@Html.ActionLink("Pedidos SAP", "search", "salesorder")</li>
                                    <li>@Html.ActionLink("Inventario por producto", "itemstock", "salesorder")</li>
                                    <li>@Html.ActionLink("Nueva cotización", "create", "Quotation")</li>
                                }
                                @if (purchaseOrderCreator || orderApprover)
                                {
                                    <li>@Html.ActionLink("Autorizaciones", "AuthorizationReport", "salesorder")</li>
                                    if (orderApprover)
                                    {
                                        <li>@Html.ActionLink("Reporte autorizaciones", "AuthorizationDetailReport", "salesorder")</li>
                                    }
                                }
                                @if (supervisor)
                                {
                                    <li>@Html.ActionLink("Resumen ventas", "SupervisorDashboard", "salesorder")</li>
                                }
                            </ul>
                        </li>




                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Gestíon clientes<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                @if (customerCreator)
                                {

                                    <li>@Html.ActionLink("Clientes", "index", "customer")</li>

                                }
                                <li><a href="@Url.Action("CustomerPaymentAges", "Customer")">Edades de cartera por cliente</a></li>
                                <li><a href="@Url.Action("lastPrices", "Customer")">Reporte últimos precios</a></li>
                            </ul>
                        </li>

                        @if (admin)
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administración<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="@Url.Action("Index", "Company")">Compañias</a></li>
                                    <li><a href="@Url.Action("Index", "WebUser")">Usuarios</a></li>
                                    <li><a href="@Url.Action("georeport", "salesorder")">Reporte geográfico</a></li>
                                </ul>
                            </li>
                        }
                        @*<li><a href="javascript:void(0);">@User.Identity.GetUserName()</a></li>*@
                            @*<li><a href="@Url.Action("LogOut", "Security")">Cerrar sesión</a></li>*@
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="javascript:void(0);">@User.Identity.GetUserName() - @company</a></li>
                            <li><a href="@Url.Action("LogOut", "Security")">Cerrar sesión</a></li>
                        </ul>
                }



                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <div class="footer">
        <span>.::. © 2015 Grupo Bretano .::. Desarrollado por <a href="http://www.orkidea.co">OrkIdea SAS</a> .::. </span>
    </div>
    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>